
import React from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { FileText, Link as LinkIcon } from 'lucide-react';
import { Link } from 'react-router-dom';

const Terms = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-grow">
        {/* Hero Section */}
        <div className="bg-gradient-to-b from-purple-50 to-white">
          <div className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
            <div className="text-center">
              <FileText className="mx-auto h-16 w-16 text-primary" />
              <h1 className="mt-4 text-4xl font-extrabold text-gray-900 sm:text-5xl">
                Terms of Service
              </h1>
              <p className="mt-4 max-w-3xl mx-auto text-lg text-gray-500">
                Last updated: May 1, 2025
              </p>
            </div>
          </div>
        </div>

        {/* Terms Content */}
        <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
          <div className="prose prose-lg mx-auto">
            <h2>1. Agreement to Terms</h2>
            <p>
              By accessing or using CourseGPT's website, services, or any applications (collectively, the "Service") provided by CourseGPT 
              ("we", "us", or "our"), you agree to be bound by these Terms of Service ("Terms"). If you don't agree to these Terms, 
              you may not access or use the Service.
            </p>

            <h2>2. Changes to Terms</h2>
            <p>
              We may modify the Terms at any time, at our sole discretion. If we do so, we'll let you know either by posting the modified Terms 
              on the site or through other communications. It's important that you review the Terms whenever we modify them because if you continue 
              to use the Service after we have posted modified Terms, you are indicating to us that you agree to be bound by the modified Terms.
            </p>

            <h2>3. Accessing the Service</h2>
            <p>
              To access and use certain features of the Service, you need to create an account. You must provide accurate, current, 
              and complete information during the registration process and keep your account information up-to-date.
            </p>
            <p>
              You are responsible for safeguarding the password that you use to access the Service and for any activities or actions 
              under your account. We encourage you to use a strong password (a combination of upper and lower case letters, 
              numbers, and symbols) with your account.
            </p>

            <h2>4. Our Service</h2>
            <p>
              CourseGPT provides an AI-powered platform for creating, organizing, and managing educational content. 
              Our Service allows users to:
            </p>
            <ul>
              <li>Create educational courses using AI-assisted tools</li>
              <li>Organize educational material into structured courses</li>
              <li>Generate content suggestions and enhancements</li>
              <li>Publish and share courses</li>
              <li>Track learner progress and engagement</li>
            </ul>

            <h2>5. Content and Content Rights</h2>
            <h3>5.1. User Content</h3>
            <p>
              Content generated, uploaded, or created by you while using our Service is referred to as "User Content." 
              You retain all rights in, and are solely responsible for, the User Content you create, upload, post, 
              send, or store through the Service.
            </p>

            <h3>5.2. License to CourseGPT</h3>
            <p>
              By submitting User Content through the Service, you grant CourseGPT a worldwide, non-exclusive, royalty-free, 
              fully paid, sublicensable, and transferable license to use, reproduce, modify, adapt, publish, translate, 
              create derivative works from, distribute, publicly perform, and display your User Content, in whole or in part, 
              in connection with the operation, provision, and improvement of the Service.
            </p>

            <h3>5.3. AI-Generated Content</h3>
            <p>
              Content generated by our AI is provided "as is" without any guarantees of accuracy or completeness. 
              CourseGPT does not claim ownership of AI-generated content that is part of your course, 
              but we retain all rights to our AI technology and models.
            </p>
            <p>
              You are responsible for reviewing and editing AI-generated content to ensure it meets your standards 
              and complies with applicable laws and regulations.
            </p>

            <h2>6. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Violate any laws or regulations</li>
              <li>Infringe upon the rights of others or violate their privacy</li>
              <li>Generate or distribute harmful, abusive, racist, or otherwise objectionable content</li>
              <li>Send spam or unsolicited communications</li>
              <li>Interfere with or disrupt the integrity or performance of the Service</li>
              <li>Attempt to gain unauthorized access to the Service or its related systems</li>
              <li>Use the Service for unauthorized commercial purposes</li>
            </ul>

            <h2>7. Subscriptions and Payments</h2>
            <p>
              Some features of the Service require payment of fees. You will be charged in accordance with the pricing 
              plan you select. We may change our prices at any time, but we'll provide you with notice of any price changes.
            </p>
            <p>
              All payments are non-refundable except as expressly set forth in these Terms or as required by applicable law.
            </p>

            <h2>8. Intellectual Property Rights</h2>
            <p>
              The Service and its original content, features, and functionality are owned by CourseGPT and are protected 
              by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.
            </p>

            <h2>9. Termination</h2>
            <p>
              We may terminate or suspend your account and access to the Service at our sole discretion, without 
              prior notice or liability, for any reason, including, but not limited to, breach of these Terms.
            </p>
            <p>
              All provisions of the Terms that by their nature should survive termination shall survive termination, 
              including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.
            </p>

            <h2>10. Disclaimer</h2>
            <p>
              THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. COURSEGPT EXPRESSLY DISCLAIMS ALL 
              WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
              OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>

            <h2>11. Limitation of Liability</h2>
            <p>
              IN NO EVENT SHALL COURSEGPT, ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, SUPPLIERS, OR AFFILIATES, 
              BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT 
              LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR ACCESS 
              TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE.
            </p>

            <h2>12. Governing Law</h2>
            <p>
              These Terms shall be governed by the laws of the State of California, without respect to its conflict of laws principles.
            </p>

            <h2>13. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <p>
              <a href="mailto:legal@coursegpt.com" className="text-primary hover:underline">legal@coursegpt.com</a>
            </p>
            <p>
              <Link to="/privacy" className="inline-flex items-center text-primary hover:underline">
                <LinkIcon className="h-4 w-4 mr-1" />
                View our Privacy Policy
              </Link>
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Terms;
